<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteCvp.Application\SteCvp.Application.csproj" />
    <ProjectReference Include="..\SteCvp.Domain\SteCvp.Domain.csproj" />
  </ItemGroup>

</Project>
